### ISSUE TITLE
Implement bundle/build tool

### ISSUE THREAD

**Issue by mlajkim** [ajktown/ConsistencyGPT#41]
### Background

Use build tools to minimize the project like the following:
![image](https://github.com/ajktown/ConsistencyGPT/assets/53258958/e91735f1-3b66-4df3-9cbb-646cae7f73dd)

### TODOs

```
- [ ] Implement bundle/build tools for smaller sized packages
- [ ] Write similar issue for ajktown/api
- [ ] Write similar issue for ajktown/wordnote
```
