### ISSUE TITLE
Christmas Theme

### ISSUE THREAD

**Issue by mlajkim** [ajktown/ConsistencyGPT#71]
### Background
Halloween theme is developed:
https://github.com/ajktown/ConsistencyGPT/issues/69

Let's create the Christmas Theme too!
![image](https://github.com/user-attachments/assets/f9deca30-91b9-4ef5-a17e-9a849aa2bf22)

during the test, you might have to directly modify by commenting out `default: defaultTheme` and directly set `AppTheme.Christmas`
https://github.com/ajktown/ConsistencyGPT/blob/684b1f890817f18a110693c6fc5edb4d6a6dc675/src/recoil/app-theme/app-theme.state.ts#L38-L39

### TODOs

- [x] Get a cute Christmas Icon in PNG format
  - Like this: https://github.com/ajktown/ConsistencyGPT/blob/main/public/app_theme/halloween-cute-pumpkin.png
- [x] Apply the PNG icon in src/components/organism_appbar/index.main-logo.tsx
- [x] Define `Christmas` in enum `AppTheme` in src/recoil/app-theme/app-theme.state.ts
- [x] Define `const christmas = DateTime.fromObject({ month: 12, day: 25 }).endOf(`day`)` in src/recoil/app-theme/app-theme.state.ts
- [x] Create a new color for `enum Christmas { ... }` in src/lambdas/get-app-theme-color.lambda.ts
- [x] Modify `getAppThemeColorLambda` with enum Christmas in src/lambdas/get-app-theme-color.lambda.ts
- [x] Modify `getAppBarColorLambda` with enum Christmas in src/lambdas/get-app-theme-color.lambda.ts
- [x] Modify `getButtonColorLambda` with enum Christmas in src/lambdas/get-app-theme-color.lambda.ts

**Comment by mlajkim** [comment]
Handled in https://github.com/ajktown/ConsistencyGPT/pull/74
